//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace grd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cart
    {
        public int cartId { get; set; }
        public string userId { get; set; }
        public string bookId { get; set; }
        public string bookName { get; set; }
        public string categoryName { get; set; }
        public double price { get; set; }
        public string authorName { get; set; }
    }
}
