//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace grd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class category
    {
        public category()
        {
            this.Books = new HashSet<Book>();
        }
    
        public int catId { get; set; }
        public string catName { get; set; }
    
        public virtual ICollection<Book> Books { get; set; }
    }
}
