//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace grd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public string username { get; set; }
        public string name { get; set; }
        public string type { get; set; }
        public string email { get; set; }
        public string pass { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
    }
}
